include include/asm-generic/Kbuild.asm

header-y += ../arch/

header-y += ucontext.h
header-y += hardwall.h
header-y += cachectl.h
# From here to the blank line are currently Tilera-internal.
header-y += dataplane.h
header-y += i2cs.h
header-y += kvm_virtio.h
header-y += memprof.h
header-y += bme.h
header-y += pka.h
header-y += tilepci.h
header-y += tilegxpci.h

generic-y += bug.h
generic-y += bugs.h
generic-y += cputime.h
generic-y += div64.h
generic-y += emergency-restart.h
generic-y += errno.h
generic-y += fb.h
generic-y += fcntl.h
generic-y += hw_irq.h
generic-y += ioctl.h
generic-y += ioctls.h
generic-y += ipc.h
generic-y += ipcbuf.h
generic-y += irq_regs.h
generic-y += local.h
generic-y += local64.h
generic-y += msgbuf.h
generic-y += mutex.h
generic-y += param.h
generic-y += parport.h
generic-y += poll.h
generic-y += posix_types.h
generic-y += resource.h
generic-y += scatterlist.h
generic-y += sembuf.h
generic-y += serial.h
generic-y += shmbuf.h
generic-y += shmparam.h
generic-y += socket.h
generic-y += sockios.h
generic-y += statfs.h
generic-y += termbits.h
generic-y += termios.h
generic-y += types.h
generic-y += ucontext.h
generic-y += xor.h
